services:
  backend:
    build:
      context: ./task-manager
      dockerfile: Dockerfile
    container_name: taskmanager-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=default
    networks:
      - tasknet

  frontend:
    build:
      context: ./task-manager-ui
      dockerfile: Dockerfile
    container_name: taskmanager-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
    networks:
      - tasknet

networks:
  tasknet:
    driver: bridge
